"""empty message

Revision ID: 210d5d3385bc
Revises: 
Create Date: 2018-12-18 13:00:16.868639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '210d5d3385bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_identity', sa.String(length=32), nullable=False),
    sa.Column('ejudge_contest_id', sa.Integer(), nullable=False),
    sa.Column('ejudge_problem_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problem_problem_identity'), 'problem', ['problem_identity'], unique=True)
    op.create_table('run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_identity', sa.String(length=32), nullable=False),
    sa.Column('context_identity', sa.String(length=32), nullable=True),
    sa.Column('ejudge_identity', sa.String(length=32), nullable=True),
    sa.Column('problem_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('ej_run_id', sa.Integer(), nullable=True),
    sa.Column('ej_contest_id', sa.Integer(), nullable=True),
    sa.Column('ej_run_uuid', sa.String(length=40), nullable=True),
    sa.Column('ej_score', sa.Integer(), nullable=True),
    sa.Column('ej_status', sa.Integer(), nullable=True),
    sa.Column('ej_lang_id', sa.Integer(), nullable=True),
    sa.Column('ej_test_num', sa.Integer(), nullable=True),
    sa.Column('ej_create_time', sa.DateTime(), nullable=True),
    sa.Column('ej_last_change_time', sa.DateTime(), nullable=True),
    sa.Column('ejudge_url', sa.String(length=50), nullable=True),
    sa.Column('source_hash', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_problem_id'), 'run', ['problem_id'], unique=False)
    op.create_index(op.f('ix_run_user_identity'), 'run', ['user_identity'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_run_user_identity'), table_name='run')
    op.drop_index(op.f('ix_run_problem_id'), table_name='run')
    op.drop_table('run')
    op.drop_index(op.f('ix_problem_problem_identity'), table_name='problem')
    op.drop_table('problem')
    # ### end Alembic commands ###
